"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_source_ip_mapping import (
    VoiceV1SourceIPMapping,
    VoiceV1SourceIPMappingTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict

CREATE_SOURCE_IP_MAPPING_OP_SERVERS = [
    "https://voice.twilio.com",
]


class CreateSourceIPMappingCreateSourceIPMappingRequestTypedDict(TypedDict):
    ip_record_sid: str
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to map from."""
    sip_domain_sid: str
    r"""The SID of the SIP Domain that the IP Record should be mapped to."""


class CreateSourceIPMappingCreateSourceIPMappingRequest(BaseModel):
    ip_record_sid: Annotated[
        str, pydantic.Field(alias="IpRecordSid"), FieldMetadata(form=True)
    ]
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to map from."""

    sip_domain_sid: Annotated[
        str, pydantic.Field(alias="SipDomainSid"), FieldMetadata(form=True)
    ]
    r"""The SID of the SIP Domain that the IP Record should be mapped to."""


class CreateSourceIPMappingResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1SourceIPMappingTypedDict


class CreateSourceIPMappingResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1SourceIPMapping
