"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_dialing_permissions_dialing_permissions_country_bulk_update import (
    VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate,
    VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdateTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict

CREATE_DIALING_PERMISSIONS_COUNTRY_BULK_UPDATE_OP_SERVERS = [
    "https://voice.twilio.com",
]


class CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequestTypedDict(
    TypedDict
):
    update_request: str
    r"""URL encoded JSON array of update objects. example : `[ { \"iso_code\": \"GB\", \"low_risk_numbers_enabled\": \"true\", \"high_risk_special_numbers_enabled\":\"true\", \"high_risk_tollfraud_numbers_enabled\": \"false\" } ]`"""


class CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest(
    BaseModel
):
    update_request: Annotated[
        str, pydantic.Field(alias="UpdateRequest"), FieldMetadata(form=True)
    ]
    r"""URL encoded JSON array of update objects. example : `[ { \"iso_code\": \"GB\", \"low_risk_numbers_enabled\": \"true\", \"high_risk_special_numbers_enabled\":\"true\", \"high_risk_tollfraud_numbers_enabled\": \"false\" } ]`"""


class CreateDialingPermissionsCountryBulkUpdateResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdateTypedDict


class CreateDialingPermissionsCountryBulkUpdateResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate
