"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_ip_record import VoiceV1IPRecord, VoiceV1IPRecordTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict

CREATE_IP_RECORD_OP_SERVERS = [
    "https://voice.twilio.com",
]


class CreateIPRecordCreateIPRecordRequestTypedDict(TypedDict):
    ip_address: str
    r"""An IP address in dotted decimal notation, IPv4 only."""
    friendly_name: NotRequired[str]
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""
    cidr_prefix_length: NotRequired[int]
    r"""An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32."""


class CreateIPRecordCreateIPRecordRequest(BaseModel):
    ip_address: Annotated[
        str, pydantic.Field(alias="IpAddress"), FieldMetadata(form=True)
    ]
    r"""An IP address in dotted decimal notation, IPv4 only."""

    friendly_name: Annotated[
        Optional[str], pydantic.Field(alias="FriendlyName"), FieldMetadata(form=True)
    ] = None
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""

    cidr_prefix_length: Annotated[
        Optional[int],
        pydantic.Field(alias="CidrPrefixLength"),
        FieldMetadata(form=True),
    ] = None
    r"""An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32."""


class CreateIPRecordResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1IPRecordTypedDict


class CreateIPRecordResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1IPRecord
