"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_byoc_trunk import VoiceV1ByocTrunk, VoiceV1ByocTrunkTypedDict
from enum import Enum
from openapi.types import BaseModel
from openapi.utils import FieldMetadata
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict

CREATE_BYOC_TRUNK_OP_SERVERS = [
    "https://voice.twilio.com",
]


class CreateByocTrunkVoiceMethod(str, Enum):
    r"""The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`."""

    GET = "GET"
    POST = "POST"


class CreateByocTrunkVoiceFallbackMethod(str, Enum):
    r"""The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`."""

    GET = "GET"
    POST = "POST"


class CreateByocTrunkStatusCallbackMethod(str, Enum):
    r"""The HTTP method we should use to call `status_callback_url`. Can be: `GET` or `POST`."""

    GET = "GET"
    POST = "POST"


class CreateByocTrunkCreateByocTrunkRequestTypedDict(TypedDict):
    friendly_name: NotRequired[str]
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""
    voice_url: NotRequired[str]
    r"""The URL we should call when the BYOC Trunk receives a call."""
    voice_method: NotRequired[CreateByocTrunkVoiceMethod]
    r"""The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`."""
    voice_fallback_url: NotRequired[str]
    r"""The URL that we should call when an error occurs while retrieving or executing the TwiML from `voice_url`."""
    voice_fallback_method: NotRequired[CreateByocTrunkVoiceFallbackMethod]
    r"""The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`."""
    status_callback_url: NotRequired[str]
    r"""The URL that we should call to pass status parameters (such as call ended) to your application."""
    status_callback_method: NotRequired[CreateByocTrunkStatusCallbackMethod]
    r"""The HTTP method we should use to call `status_callback_url`. Can be: `GET` or `POST`."""
    cnam_lookup_enabled: NotRequired[bool]
    r"""Whether Caller ID Name (CNAM) lookup is enabled for the trunk. If enabled, all inbound calls to the BYOC Trunk from the United States and Canada automatically perform a CNAM Lookup and display Caller ID data on your phone. See [CNAM Lookups](https://www.twilio.com/docs/sip-trunking#CNAM) for more information."""
    connection_policy_sid: NotRequired[str]
    r"""The SID of the Connection Policy that Twilio will use when routing traffic to your communications infrastructure."""
    from_domain_sid: NotRequired[str]
    r"""The SID of the SIP Domain that should be used in the `From` header of originating calls sent to your SIP infrastructure. If your SIP infrastructure allows users to \"call back\" an incoming call, configure this with a [SIP Domain](https://www.twilio.com/docs/voice/api/sending-sip) to ensure proper routing. If not configured, the from domain will default to \"sip.twilio.com\"."""


class CreateByocTrunkCreateByocTrunkRequest(BaseModel):
    friendly_name: Annotated[
        Optional[str], pydantic.Field(alias="FriendlyName"), FieldMetadata(form=True)
    ] = None
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""

    voice_url: Annotated[
        Optional[str], pydantic.Field(alias="VoiceUrl"), FieldMetadata(form=True)
    ] = None
    r"""The URL we should call when the BYOC Trunk receives a call."""

    voice_method: Annotated[
        Optional[CreateByocTrunkVoiceMethod],
        pydantic.Field(alias="VoiceMethod"),
        FieldMetadata(form=True),
    ] = None
    r"""The HTTP method we should use to call `voice_url`. Can be: `GET` or `POST`."""

    voice_fallback_url: Annotated[
        Optional[str],
        pydantic.Field(alias="VoiceFallbackUrl"),
        FieldMetadata(form=True),
    ] = None
    r"""The URL that we should call when an error occurs while retrieving or executing the TwiML from `voice_url`."""

    voice_fallback_method: Annotated[
        Optional[CreateByocTrunkVoiceFallbackMethod],
        pydantic.Field(alias="VoiceFallbackMethod"),
        FieldMetadata(form=True),
    ] = None
    r"""The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`."""

    status_callback_url: Annotated[
        Optional[str],
        pydantic.Field(alias="StatusCallbackUrl"),
        FieldMetadata(form=True),
    ] = None
    r"""The URL that we should call to pass status parameters (such as call ended) to your application."""

    status_callback_method: Annotated[
        Optional[CreateByocTrunkStatusCallbackMethod],
        pydantic.Field(alias="StatusCallbackMethod"),
        FieldMetadata(form=True),
    ] = None
    r"""The HTTP method we should use to call `status_callback_url`. Can be: `GET` or `POST`."""

    cnam_lookup_enabled: Annotated[
        Optional[bool],
        pydantic.Field(alias="CnamLookupEnabled"),
        FieldMetadata(form=True),
    ] = None
    r"""Whether Caller ID Name (CNAM) lookup is enabled for the trunk. If enabled, all inbound calls to the BYOC Trunk from the United States and Canada automatically perform a CNAM Lookup and display Caller ID data on your phone. See [CNAM Lookups](https://www.twilio.com/docs/sip-trunking#CNAM) for more information."""

    connection_policy_sid: Annotated[
        Optional[str],
        pydantic.Field(alias="ConnectionPolicySid"),
        FieldMetadata(form=True),
    ] = None
    r"""The SID of the Connection Policy that Twilio will use when routing traffic to your communications infrastructure."""

    from_domain_sid: Annotated[
        Optional[str], pydantic.Field(alias="FromDomainSid"), FieldMetadata(form=True)
    ] = None
    r"""The SID of the SIP Domain that should be used in the `From` header of originating calls sent to your SIP infrastructure. If your SIP infrastructure allows users to \"call back\" an incoming call, configure this with a [SIP Domain](https://www.twilio.com/docs/voice/api/sending-sip) to ensure proper routing. If not configured, the from domain will default to \"sip.twilio.com\"."""


class CreateByocTrunkResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1ByocTrunkTypedDict


class CreateByocTrunkResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1ByocTrunk
