"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_connection_policy import (
    VoiceV1ConnectionPolicy,
    VoiceV1ConnectionPolicyTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict

CREATE_CONNECTION_POLICY_OP_SERVERS = [
    "https://voice.twilio.com",
]


class CreateConnectionPolicyCreateConnectionPolicyRequestTypedDict(TypedDict):
    friendly_name: NotRequired[str]
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""


class CreateConnectionPolicyCreateConnectionPolicyRequest(BaseModel):
    friendly_name: Annotated[
        Optional[str], pydantic.Field(alias="FriendlyName"), FieldMetadata(form=True)
    ] = None
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""


class CreateConnectionPolicyResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1ConnectionPolicyTypedDict


class CreateConnectionPolicyResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1ConnectionPolicy
