"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict

DELETE_BYOC_TRUNK_OP_SERVERS = [
    "https://voice.twilio.com",
]


class DeleteByocTrunkRequestTypedDict(TypedDict):
    sid: str
    r"""The Twilio-provided string that uniquely identifies the BYOC Trunk resource to delete."""


class DeleteByocTrunkRequest(BaseModel):
    sid: Annotated[
        str,
        pydantic.Field(alias="Sid"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The Twilio-provided string that uniquely identifies the BYOC Trunk resource to delete."""
