"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_source_ip_mapping import (
    VoiceV1SourceIPMapping,
    VoiceV1SourceIPMappingTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict

FETCH_SOURCE_IP_MAPPING_OP_SERVERS = [
    "https://voice.twilio.com",
]


class FetchSourceIPMappingRequestTypedDict(TypedDict):
    sid: str
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to fetch."""


class FetchSourceIPMappingRequest(BaseModel):
    sid: Annotated[
        str,
        pydantic.Field(alias="Sid"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to fetch."""


class FetchSourceIPMappingResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1SourceIPMappingTypedDict


class FetchSourceIPMappingResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1SourceIPMapping
