"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_dialing_permissions_dialing_permissions_country_instance import (
    VoiceV1DialingPermissionsDialingPermissionsCountryInstance,
    VoiceV1DialingPermissionsDialingPermissionsCountryInstanceTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict

FETCH_DIALING_PERMISSIONS_COUNTRY_OP_SERVERS = [
    "https://voice.twilio.com",
]


class FetchDialingPermissionsCountryRequestTypedDict(TypedDict):
    iso_code: str
    r"""The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the DialingPermissions Country resource to fetch"""


class FetchDialingPermissionsCountryRequest(BaseModel):
    iso_code: Annotated[
        str,
        pydantic.Field(alias="IsoCode"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the DialingPermissions Country resource to fetch"""


class FetchDialingPermissionsCountryResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1DialingPermissionsDialingPermissionsCountryInstanceTypedDict


class FetchDialingPermissionsCountryResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1DialingPermissionsDialingPermissionsCountryInstance
