"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_ip_record import VoiceV1IPRecord, VoiceV1IPRecordTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict

FETCH_IP_RECORD_OP_SERVERS = [
    "https://voice.twilio.com",
]


class FetchIPRecordRequestTypedDict(TypedDict):
    sid: str
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to fetch."""


class FetchIPRecordRequest(BaseModel):
    sid: Annotated[
        str,
        pydantic.Field(alias="Sid"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to fetch."""


class FetchIPRecordResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1IPRecordTypedDict


class FetchIPRecordResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1IPRecord
