"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_connection_policy import (
    VoiceV1ConnectionPolicy,
    VoiceV1ConnectionPolicyTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict

FETCH_CONNECTION_POLICY_OP_SERVERS = [
    "https://voice.twilio.com",
]


class FetchConnectionPolicyRequestTypedDict(TypedDict):
    sid: str
    r"""The unique string that we created to identify the Connection Policy resource to fetch."""


class FetchConnectionPolicyRequest(BaseModel):
    sid: Annotated[
        str,
        pydantic.Field(alias="Sid"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique string that we created to identify the Connection Policy resource to fetch."""


class FetchConnectionPolicyResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1ConnectionPolicyTypedDict


class FetchConnectionPolicyResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1ConnectionPolicy
