"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_dialing_permissions_dialing_permissions_settings import (
    VoiceV1DialingPermissionsDialingPermissionsSettings,
    VoiceV1DialingPermissionsDialingPermissionsSettingsTypedDict,
)
from openapi.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict

FETCH_DIALING_PERMISSIONS_SETTINGS_OP_SERVERS = [
    "https://voice.twilio.com",
]


class FetchDialingPermissionsSettingsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1DialingPermissionsDialingPermissionsSettingsTypedDict


class FetchDialingPermissionsSettingsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1DialingPermissionsDialingPermissionsSettings
