"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_source_ip_mapping import (
    VoiceV1SourceIPMapping,
    VoiceV1SourceIPMappingTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict

UPDATE_SOURCE_IP_MAPPING_OP_SERVERS = [
    "https://voice.twilio.com",
]


class UpdateSourceIPMappingUpdateSourceIPMappingRequestTypedDict(TypedDict):
    sip_domain_sid: str
    r"""The SID of the SIP Domain that the IP Record should be mapped to."""


class UpdateSourceIPMappingUpdateSourceIPMappingRequest(BaseModel):
    sip_domain_sid: Annotated[
        str, pydantic.Field(alias="SipDomainSid"), FieldMetadata(form=True)
    ]
    r"""The SID of the SIP Domain that the IP Record should be mapped to."""


class UpdateSourceIPMappingRequestTypedDict(TypedDict):
    sid: str
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to update."""
    request_body: NotRequired[
        UpdateSourceIPMappingUpdateSourceIPMappingRequestTypedDict
    ]


class UpdateSourceIPMappingRequest(BaseModel):
    sid: Annotated[
        str,
        pydantic.Field(alias="Sid"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to update."""

    request_body: Annotated[
        Optional[UpdateSourceIPMappingUpdateSourceIPMappingRequest],
        FieldMetadata(
            request=RequestMetadata(media_type="application/x-www-form-urlencoded")
        ),
    ] = None


class UpdateSourceIPMappingResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1SourceIPMappingTypedDict


class UpdateSourceIPMappingResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1SourceIPMapping
