"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_ip_record import VoiceV1IPRecord, VoiceV1IPRecordTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict

UPDATE_IP_RECORD_OP_SERVERS = [
    "https://voice.twilio.com",
]


class UpdateIPRecordUpdateIPRecordRequestTypedDict(TypedDict):
    friendly_name: NotRequired[str]
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""


class UpdateIPRecordUpdateIPRecordRequest(BaseModel):
    friendly_name: Annotated[
        Optional[str], pydantic.Field(alias="FriendlyName"), FieldMetadata(form=True)
    ] = None
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""


class UpdateIPRecordRequestTypedDict(TypedDict):
    sid: str
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to update."""
    request_body: NotRequired[UpdateIPRecordUpdateIPRecordRequestTypedDict]


class UpdateIPRecordRequest(BaseModel):
    sid: Annotated[
        str,
        pydantic.Field(alias="Sid"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The Twilio-provided string that uniquely identifies the IP Record resource to update."""

    request_body: Annotated[
        Optional[UpdateIPRecordUpdateIPRecordRequest],
        FieldMetadata(
            request=RequestMetadata(media_type="application/x-www-form-urlencoded")
        ),
    ] = None


class UpdateIPRecordResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1IPRecordTypedDict


class UpdateIPRecordResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1IPRecord
