"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_connection_policy import (
    VoiceV1ConnectionPolicy,
    VoiceV1ConnectionPolicyTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict

UPDATE_CONNECTION_POLICY_OP_SERVERS = [
    "https://voice.twilio.com",
]


class UpdateConnectionPolicyUpdateConnectionPolicyRequestTypedDict(TypedDict):
    friendly_name: NotRequired[str]
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""


class UpdateConnectionPolicyUpdateConnectionPolicyRequest(BaseModel):
    friendly_name: Annotated[
        Optional[str], pydantic.Field(alias="FriendlyName"), FieldMetadata(form=True)
    ] = None
    r"""A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long."""


class UpdateConnectionPolicyRequestTypedDict(TypedDict):
    sid: str
    r"""The unique string that we created to identify the Connection Policy resource to update."""
    request_body: NotRequired[
        UpdateConnectionPolicyUpdateConnectionPolicyRequestTypedDict
    ]


class UpdateConnectionPolicyRequest(BaseModel):
    sid: Annotated[
        str,
        pydantic.Field(alias="Sid"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique string that we created to identify the Connection Policy resource to update."""

    request_body: Annotated[
        Optional[UpdateConnectionPolicyUpdateConnectionPolicyRequest],
        FieldMetadata(
            request=RequestMetadata(media_type="application/x-www-form-urlencoded")
        ),
    ] = None


class UpdateConnectionPolicyResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1ConnectionPolicyTypedDict


class UpdateConnectionPolicyResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1ConnectionPolicy
