"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voice_v1_dialing_permissions_dialing_permissions_settings import (
    VoiceV1DialingPermissionsDialingPermissionsSettings,
    VoiceV1DialingPermissionsDialingPermissionsSettingsTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict

UPDATE_DIALING_PERMISSIONS_SETTINGS_OP_SERVERS = [
    "https://voice.twilio.com",
]


class UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequestTypedDict(
    TypedDict
):
    dialing_permissions_inheritance: NotRequired[bool]
    r"""`true` for the sub-account to inherit voice dialing permissions from the Master Project; otherwise `false`."""


class UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest(
    BaseModel
):
    dialing_permissions_inheritance: Annotated[
        Optional[bool],
        pydantic.Field(alias="DialingPermissionsInheritance"),
        FieldMetadata(form=True),
    ] = None
    r"""`true` for the sub-account to inherit voice dialing permissions from the Master Project; otherwise `false`."""


class UpdateDialingPermissionsSettingsResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: VoiceV1DialingPermissionsDialingPermissionsSettingsTypedDict


class UpdateDialingPermissionsSettingsResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: VoiceV1DialingPermissionsDialingPermissionsSettings
