"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class VoiceV1DialingPermissionsDialingPermissionsSettingsTypedDict(TypedDict):
    dialing_permissions_inheritance: NotRequired[Nullable[bool]]
    r"""`true` if the sub-account will inherit voice dialing permissions from the Master Project; otherwise `false`."""
    url: NotRequired[Nullable[str]]
    r"""The absolute URL of this resource."""


class VoiceV1DialingPermissionsDialingPermissionsSettings(BaseModel):
    dialing_permissions_inheritance: OptionalNullable[bool] = UNSET
    r"""`true` if the sub-account will inherit voice dialing permissions from the Master Project; otherwise `false`."""

    url: OptionalNullable[str] = UNSET
    r"""The absolute URL of this resource."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["dialing_permissions_inheritance", "url"]
        nullable_fields = ["dialing_permissions_inheritance", "url"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
