"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VoiceV1IPRecordTypedDict(TypedDict):
    account_sid: NotRequired[Nullable[str]]
    r"""The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource."""
    sid: NotRequired[Nullable[str]]
    r"""The unique string that we created to identify the IP Record resource."""
    friendly_name: NotRequired[Nullable[str]]
    r"""The string that you assigned to describe the resource."""
    ip_address: NotRequired[Nullable[str]]
    r"""An IP address in dotted decimal notation, IPv4 only."""
    cidr_prefix_length: NotRequired[int]
    r"""An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32."""
    date_created: NotRequired[Nullable[datetime]]
    r"""The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format."""
    date_updated: NotRequired[Nullable[datetime]]
    r"""The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format."""
    url: NotRequired[Nullable[str]]
    r"""The absolute URL of the resource."""


class VoiceV1IPRecord(BaseModel):
    account_sid: OptionalNullable[str] = UNSET
    r"""The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource."""

    sid: OptionalNullable[str] = UNSET
    r"""The unique string that we created to identify the IP Record resource."""

    friendly_name: OptionalNullable[str] = UNSET
    r"""The string that you assigned to describe the resource."""

    ip_address: OptionalNullable[str] = UNSET
    r"""An IP address in dotted decimal notation, IPv4 only."""

    cidr_prefix_length: Optional[int] = 0
    r"""An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32."""

    date_created: OptionalNullable[datetime] = UNSET
    r"""The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format."""

    date_updated: OptionalNullable[datetime] = UNSET
    r"""The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format."""

    url: OptionalNullable[str] = UNSET
    r"""The absolute URL of the resource."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "account_sid",
            "sid",
            "friendly_name",
            "ip_address",
            "cidr_prefix_length",
            "date_created",
            "date_updated",
            "url",
        ]
        nullable_fields = [
            "account_sid",
            "sid",
            "friendly_name",
            "ip_address",
            "date_created",
            "date_updated",
            "url",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
