"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VoiceV1ConnectionPolicyConnectionPolicyTargetTypedDict(TypedDict):
    account_sid: NotRequired[Nullable[str]]
    r"""The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Target resource."""
    connection_policy_sid: NotRequired[Nullable[str]]
    r"""The SID of the Connection Policy that owns the Target."""
    sid: NotRequired[Nullable[str]]
    r"""The unique string that we created to identify the Target resource."""
    friendly_name: NotRequired[Nullable[str]]
    r"""The string that you assigned to describe the resource."""
    target: NotRequired[Nullable[str]]
    r"""The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported."""
    priority: NotRequired[int]
    r"""The relative importance of the target. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important target."""
    weight: NotRequired[int]
    r"""The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. Targets with higher values receive more load than those with lower ones with the same priority."""
    enabled: NotRequired[Nullable[bool]]
    r"""Whether the target is enabled. The default is `true`."""
    date_created: NotRequired[Nullable[datetime]]
    r"""The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format."""
    date_updated: NotRequired[Nullable[datetime]]
    r"""The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format."""
    url: NotRequired[Nullable[str]]
    r"""The absolute URL of the resource."""


class VoiceV1ConnectionPolicyConnectionPolicyTarget(BaseModel):
    account_sid: OptionalNullable[str] = UNSET
    r"""The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Target resource."""

    connection_policy_sid: OptionalNullable[str] = UNSET
    r"""The SID of the Connection Policy that owns the Target."""

    sid: OptionalNullable[str] = UNSET
    r"""The unique string that we created to identify the Target resource."""

    friendly_name: OptionalNullable[str] = UNSET
    r"""The string that you assigned to describe the resource."""

    target: OptionalNullable[str] = UNSET
    r"""The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported."""

    priority: Optional[int] = 0
    r"""The relative importance of the target. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important target."""

    weight: Optional[int] = 0
    r"""The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. Targets with higher values receive more load than those with lower ones with the same priority."""

    enabled: OptionalNullable[bool] = UNSET
    r"""Whether the target is enabled. The default is `true`."""

    date_created: OptionalNullable[datetime] = UNSET
    r"""The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format."""

    date_updated: OptionalNullable[datetime] = UNSET
    r"""The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format."""

    url: OptionalNullable[str] = UNSET
    r"""The absolute URL of the resource."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "account_sid",
            "connection_policy_sid",
            "sid",
            "friendly_name",
            "target",
            "priority",
            "weight",
            "enabled",
            "date_created",
            "date_updated",
            "url",
        ]
        nullable_fields = [
            "account_sid",
            "connection_policy_sid",
            "sid",
            "friendly_name",
            "target",
            "enabled",
            "date_created",
            "date_updated",
            "url",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
