"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class VoiceV1DialingPermissionsDialingPermissionsCountryInstanceLinksTypedDict(
    TypedDict
):
    r"""A list of URLs related to this resource."""


class VoiceV1DialingPermissionsDialingPermissionsCountryInstanceLinks(BaseModel):
    r"""A list of URLs related to this resource."""


class VoiceV1DialingPermissionsDialingPermissionsCountryInstanceTypedDict(TypedDict):
    iso_code: NotRequired[Nullable[str]]
    r"""The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)."""
    name: NotRequired[Nullable[str]]
    r"""The name of the country."""
    continent: NotRequired[Nullable[str]]
    r"""The name of the continent in which the country is located."""
    country_codes: NotRequired[Nullable[List[str]]]
    r"""The E.164 assigned [country codes(s)](https://www.itu.int/itudoc/itu-t/ob-lists/icc/e164_763.html)"""
    low_risk_numbers_enabled: NotRequired[Nullable[bool]]
    r"""Whether dialing to low-risk numbers is enabled."""
    high_risk_special_numbers_enabled: NotRequired[Nullable[bool]]
    r"""Whether dialing to high-risk special services numbers is enabled. These prefixes include number ranges allocated by the country and include premium numbers, special services, shared cost, and others"""
    high_risk_tollfraud_numbers_enabled: NotRequired[Nullable[bool]]
    r"""Whether dialing to high-risk [toll fraud](https://www.twilio.com/blog/how-to-protect-your-account-from-toll-fraud-with-voice-dialing-geo-permissions-html) numbers is enabled. These prefixes include narrow number ranges that have a high-risk of international revenue sharing fraud (IRSF) attacks, also known as [toll fraud](https://www.twilio.com/blog/how-to-protect-your-account-from-toll-fraud-with-voice-dialing-geo-permissions-html). These prefixes are collected from anti-fraud databases and verified by analyzing calls on our network. These prefixes are not available for download and are updated frequently"""
    url: NotRequired[Nullable[str]]
    r"""The absolute URL of this resource."""
    links: NotRequired[
        Nullable[
            VoiceV1DialingPermissionsDialingPermissionsCountryInstanceLinksTypedDict
        ]
    ]
    r"""A list of URLs related to this resource."""


class VoiceV1DialingPermissionsDialingPermissionsCountryInstance(BaseModel):
    iso_code: OptionalNullable[str] = UNSET
    r"""The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)."""

    name: OptionalNullable[str] = UNSET
    r"""The name of the country."""

    continent: OptionalNullable[str] = UNSET
    r"""The name of the continent in which the country is located."""

    country_codes: OptionalNullable[List[str]] = UNSET
    r"""The E.164 assigned [country codes(s)](https://www.itu.int/itudoc/itu-t/ob-lists/icc/e164_763.html)"""

    low_risk_numbers_enabled: OptionalNullable[bool] = UNSET
    r"""Whether dialing to low-risk numbers is enabled."""

    high_risk_special_numbers_enabled: OptionalNullable[bool] = UNSET
    r"""Whether dialing to high-risk special services numbers is enabled. These prefixes include number ranges allocated by the country and include premium numbers, special services, shared cost, and others"""

    high_risk_tollfraud_numbers_enabled: OptionalNullable[bool] = UNSET
    r"""Whether dialing to high-risk [toll fraud](https://www.twilio.com/blog/how-to-protect-your-account-from-toll-fraud-with-voice-dialing-geo-permissions-html) numbers is enabled. These prefixes include narrow number ranges that have a high-risk of international revenue sharing fraud (IRSF) attacks, also known as [toll fraud](https://www.twilio.com/blog/how-to-protect-your-account-from-toll-fraud-with-voice-dialing-geo-permissions-html). These prefixes are collected from anti-fraud databases and verified by analyzing calls on our network. These prefixes are not available for download and are updated frequently"""

    url: OptionalNullable[str] = UNSET
    r"""The absolute URL of this resource."""

    links: OptionalNullable[
        VoiceV1DialingPermissionsDialingPermissionsCountryInstanceLinks
    ] = UNSET
    r"""A list of URLs related to this resource."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "iso_code",
            "name",
            "continent",
            "country_codes",
            "low_risk_numbers_enabled",
            "high_risk_special_numbers_enabled",
            "high_risk_tollfraud_numbers_enabled",
            "url",
            "links",
        ]
        nullable_fields = [
            "iso_code",
            "name",
            "continent",
            "country_codes",
            "low_risk_numbers_enabled",
            "high_risk_special_numbers_enabled",
            "high_risk_tollfraud_numbers_enabled",
            "url",
            "links",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
